name: markdown autodocs
on: [push, pull_request]
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Concat document files
        uses: bayssmekanique/action-md-concat@v1
        with:
          srcDir: ./files
          destFile: ./fullDoc.md
